---
title: "397_1"
output: pdf_document
date: "2026-02-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}

make_wigner <- function(n, type = "gaussian") {
  M <- matrix(0, n, n)
  
  if (type == "gaussian") {
    vals <- rnorm(n * (n + 1) / 2, mean = 0, sd = 1)
  } else if (type == "uniform") {
    vals <- sqrt(3) * runif(n * (n + 1) / 2, min = -1, max = 1)
  } else if (type == "bernoulli") {
    vals <- sample(c(-1, 1), n * (n + 1) / 2, replace = TRUE)
  }
  
  M[upper.tri(M, diag = TRUE)] <- vals
  M <- M + t(M) - diag(diag(M))
  
  W <- M / sqrt(n)
  return(W)
}

semicircle <- function(x) {
  ifelse(abs(x) <= 2, sqrt(4 - x^2) / (2 * pi), 0)
}

n <- 400

eig_gaussian <- eigen(make_wigner(n, "gaussian"), symmetric = TRUE, only.values = TRUE)$values
eig_uniform <- eigen(make_wigner(n, "uniform"), symmetric = TRUE, only.values = TRUE)$values
eig_bernoulli <- eigen(make_wigner(n, "bernoulli"), symmetric = TRUE, only.values = TRUE)$values

breaks <- seq(-2.1, 2.1, length.out = 60)

hist(eig_gaussian,
     breaks = breaks,
     probability = TRUE,
     col = rgb(0.2, 0.4, 0.8, 0.25),
     border = NA,
     xlim = c(-2.1, 2.1),
     ylim = c(0, 0.6),
     main = "Universality of Eigenvalue Distribution",
     xlab = "Eigenvalue",
     ylab = "Density")

hist(eig_uniform,
     breaks = breaks,
     probability = TRUE,
     col = rgb(1.0, 0.6, 0.2, 0.25),
     border = NA,
     add = TRUE)

hist(eig_bernoulli,
     breaks = breaks,
     probability = TRUE,
     col = rgb(0.2, 0.7, 0.2, 0.25),
     border = NA,
     add = TRUE)

curve(semicircle(x),
      from = -2,
      to = 2,
      add = TRUE,
      col = "red",
      lwd = 3)

legend("topright",
       legend = c("Gaussian", "Uniform", "Bernoulli", "Semicircle"),
       fill = c(rgb(0.2, 0.4, 0.8, 0.25),
                rgb(1.0, 0.6, 0.2, 0.25),
                rgb(0.2, 0.7, 0.2, 0.25),
                NA),
       border = NA,
       lty = c(NA, NA, NA, 1),
       lwd = c(NA, NA, NA, 3),
       col = c(NA, NA, NA, "red"),
       cex = 0.9)
```

```{r}

make_wigner <- function(n) {
  M <- matrix(rnorm(n * n), nrow = n)
  M <- (M + t(M)) / sqrt(2)
  W <- M / sqrt(n)
  return(W)
}

semicircle <- function(x) {
  ifelse(abs(x) <= 2, sqrt(4 - x^2) / (2 * pi), 0)
}


Ns <- c(50, 200, 800)

par(mfrow = c(1, 3))

for (n in Ns) {
  W <- make_wigner(n)
  eigvals <- eigen(W, symmetric = TRUE, only.values = TRUE)$values
  
  hist(eigvals,
       breaks = 40,
       probability = TRUE,
       xlim = c(-2.5, 2.5),
       ylim = c(0, 0.45),
       main = paste("n =", n),
       xlab = "Eigenvalue",
       ylab = "Density",
       col = "gray80",
       border = "white")
  
  curve(semicircle(x),
        from = -2,
        to = 2,
        add = TRUE,
        col = "red",
        lwd = 2)
}

par(mfrow = c(1, 1))
```


```{r}
stieltjes_density <- function(x_grid, eigvals, eta) {
  values <- numeric(length(x_grid))
  
  for (j in seq_along(x_grid)) {
    z <- x_grid[j] - 1i * eta
    m_n <- mean(1 / (z - eigvals))
    values[j] <- Im(m_n) / pi
  }
  
  return(values)
}

n <- 400
W <- make_wigner(n)
eigvals <- eigen(W, symmetric = TRUE, only.values = TRUE)$values

x_grid <- seq(-3, 3, length.out = 600)
etas <- c(1 / n, 1 / sqrt(n), 0.5)

par(mfrow = c(1, 3))

for (eta in etas) {
  approx_density <- stieltjes_density(x_grid, eigvals, eta)
  
  plot(x_grid, approx_density,
       type = "l",
       lwd = 2,
       xlim = c(-3, 3),
       ylim = c(0, 1.2),
       main = paste("eta =", round(eta, 4)),
       xlab = "x",
       ylab = "Density")
  
  lines(x_grid,
        semicircle(x_grid),
        col = "red",
        lwd = 2,
        lty = 2)
  
  legend("topright",
         legend = c("Stieltjes approximation", "Semicircle"),
         lty = c(1, 2),
         lwd = 2,
         col = c("black", "red"),
         cex = 0.75)
}

par(mfrow = c(1, 1))
```

